openapi: 3.0.0
servers:
  - url: /ewb/energy/profiles/api
info:
  version: 1.7.1
  title: EWB Energy Profiles API
  license:
    name: Zeppelin Bend
tags:
  - name: Energy Profiles v1
paths:
  /v1/max-demand/{fromAsset}:
    $ref: 'v1-route-max-demand-from.yaml'
  /v1/max-demand:
    $ref: 'v1-route-max-demand-multi.yaml'
  /v1/max-demand/combine:
    $ref: 'v1-route-max-demand-combine.yaml'
  /v1/min-demand/{fromAsset}:
    $ref: 'v1-route-min-demand-from.yaml'
  /v1/range/{fromAsset}/from-date/{fromDate}/to-date/{toDate}:
    $ref: 'v1-route-range.yaml'
  /v1/weather/{fromAsset}/season/{season}/day/{dayType}/temperature/{temperature}/variance/{variance}:
    $ref: 'v1-route-weather.yaml'
  /v1/find-names/{seach}:
    $ref: 'v1-route-find-names.yaml'
  /v1/cached/{cacheKey}:
    $ref: 'v1-route-cached-result.yaml'
