swagger: "2.0"
info:
  title: "Customer Details"
  version: "1.0.0"
  description: "Request customer details from CRM for display in EDNAR."
tags:
  - name: "customerDetails"
    description: "Customer detail requests by NMI"
paths:
  /customers:
    get:
      tags:
        - "customerDetails"
      summary: "Used to retrieve customer details for one NMI/ICP."
      operationId: "Get Customer Details by NMI/ICP"
      parameters:
        - in: "query"
          name: "nmi"
          description: "The NMI of the customer whose details are being requested."
          required: true
          type: "integer"
      responses:
        "200":
          description: "The customer details for the requested NMI."
          x-amf-mediaType: "application/json"
          schema:
            $ref: "#/definitions/CustomerDetail"
  /customers/list:
    post:
      summary: "Used to retrieve customer details for multiple NMIs/ICPs."
      tags:
        - "customerDetails"
      operationId: "Retrieve a list of customer based on a list of NMIs/ICPs"
      parameters:
        - in: "body"
          x-amf-mediaType: "application/json"
          name: "nmis"
          description: "The list of NMIs of the customers whose details are being requested."
          required:
            - "nmis"
          schema:
            $ref: "#/definitions/NMIs"
      responses:
        "200":
          description: "A list of customer detail objects (one for each requested NMI)."
          x-amf-mediaType: "application/json"
          schema:
            $ref: "#/definitions/CustomerList"
definitions:
  CustomerDetail:
    x-amf-examples:
      output:
        value:
          nmi: 6430342245,
          meterNumber: 0
          moveInDate: "11/03/2021"
          lifeSupportFlag: true
          distributor: "powercor"
          customerType: "Residential"
          serviceAddress:
            unitNumber: "2B"
            streetNumber: "18"
            streetName: "High Street"
            suburb: "Richmond"
            postcode: 3023
          contact: [
          {
            id: "salesforce-id-0001",
            type: "RP",
            firstName: "Steve",
            lastName: "Smith",
            postalAddress:
              {
                unitNumber: "2B",
                streetNumber: "18",
                streetName: "High Street",
                suburb: "Richmond",
                postcode: 3023
              },
            preferredPhone: "mobile2",
            preferredEmail: "email",
            method: [
            {
              type: "Phone",
              description: "mobile",
              value: "0434000000"
            },
            {
              type: "Phone",
              description: "mobile2",
              value: "0434000009"
            },
            {
              type: "Phone",
              description: "home",
              value: "03 9876 7363"
            },
            {
              type: "Email",
              description: "email",
              value: "steve@gmail.com"
            },
            {
              type: "Email",
              description: "email1",
              value: "steve1@gmail.com"
            }
            ]
          },
          {
            id: "salesforce-id-0002",
            type: "LSC",
            firstName: "David",
            lastName: "Smith",
            postalAddress: {
              unitNumber: "2B",
              streetNumber: "18",
              streetName: "High Street",
              suburb: "Richmond",
              postcode: 3023
            },
            lifeSupportCarerAddress: {
              unitNumber: "1",
              streetNumber: "10",
              streetName: "High Street",
              suburb: "Richmond",
              postcode: 3023
            },
            method: [
            {
              type: "Phone",
              description: "mobile",
              value: "0434000001"
            },
            {
              type: "Phone",
              description: "home",
              value: "03 9876 7364"
            },
            {
              type: "Email",
              description: "email",
              value: "david@gmail.com"
            }
            ]
          }
          ]
    type: "object"
    additionalProperties: true
    required:
      - "nmi"
      - "meterNumber"
      - "moveInDate"
      - "lifeSupportFlag"
      - "distributor"
      - "customerType"
      - "serviceAddress"
      - "contact"
    properties: {
      nmi: {
        type: "integer"
      },
      meterNumber: {
        type: "integer"
      },
      moveInDate: {
        type: "string"
      },
      lifeSupportFlag: {
        type: "boolean"
      },
      distributor: {
        type: "string"
      },
      customerType: {
        type: "string"
      },
      serviceAddress: {
        $ref: "#/definitions/address"
      },
      contact: {
        type: "array",
        minItems: 1,
        items: {
          $ref: "#/definitions/contact"
        }
      }
    }
  NMIs:
    x-amf-examples:
      input:
        nmis: [
        {
          nmi: 6430342245
        },
        {
          nmi: 6430341122
        }
        ]
    type: "object"
    additionalProperties: true
    required:
      - "nmis"
    properties: {
      nmis: {
        type: "array",
        items: {
          $ref: "#/definitions/nmi"
        }
      }
    }
  CustomerList:
    x-amf-examples:
      output: {
        nmis: [
        {
          nmi: 6430342245,
          interestedPartiesFlag: true,
          lifeSupportFlag: true,
          distributor: "Powercor",
          serviceAddress: {
            unitNumber: "2B",
            streetNumber: "18",
            streetName: "High Street",
            suburb: "Richmond",
            postcode: 3023
          },
          contact: [
          {
            id: "salesforce-id-5678",
            type: "RP",
            firstName: "Steve",
            lastName: "Smith"
          }
          ]
        },
        {
          nmi: 6430341122,
          interestedPartiesFlag: false,
          lifeSupportFlag: true,
          distributor: "Powercor",
          serviceAddress: {
            unitNumber: "1A",
            streetNumber: "16",
            streetName: "High Street",
            suburb: "Richmond",
            postcode: 3023
          },
          contact: [
          {
            id: "salesforce-id-1234",
            type: "RP",
            firstName: "Steve",
            lastName: "Smith"
          }
          ]
        }
        ]
      }
    type: "object"
    additionalProperties: true,
    required:
      - "nmis"
    properties: {
      nmis: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
          required: [
            "nmi",
            "interestedPartiesFlag",
            "lifeSupportFlag",
            "distributor",
            "serviceAddress",
            "contact"
          ],
          properties: {
            nmi: {
              type: "integer"
            },
            interestedPartiesFlag: {
              type: "boolean"
            },
            lifeSupportFlag: {
              type: "boolean"
            },
            distributor: {
              type: "string"
            },
            serviceAddress: {
              $ref: "#/definitions/address"
            },
            contact: {
              type: "array",
              items: {
                $ref: "#/definitions/contact"
              }
            }
          }
        }
      }
    }
  address:
    type: "object"
    additionalProperties: true
    required:
      - "unitNumber"
      - "streetNumber"
      - "streetName"
      - "suburb"
      - "postcode"
    properties: {
      unitNumber: {
        type: "string"
      },
      streetNumber: {
        type: "string"
      },
      streetName: {
        type: "string"
      },
      suburb: {
        type: "string"
      },
      postcode: {
        type: "integer"
      }
    }
  contact:
    type: "object"
    additionalProperties: true
    required:
      - "id"
      - "type"
      - "firstName"
      - "lastName"
    properties: {
      id: {
        type: "string"
      },
      type: {
        enum: [
          "RP",
          "LSC"
        ],
        type: "string"
      },
      firstName: {
        type: "string"
      },
      lastName: {
        type: "string"
      },
      postalAddress: {
        $ref: "#/definitions/address"
      },
      lifeSupportCarerAddress: {
        $ref: "#/definitions/address"
      },
      preferredPhone: {
        type: "string"
      },
      preferredEmail: {
        type: "string"
      },
      method: {
        type: "array",
        minItems: 0,
        items: {
          type: "object",
          additionalProperties: true,
          required: [
            "type",
            "description",
            "value"
          ],
          properties: {
            type: {
              enum: [
                "Phone",
                "Email"
              ],
              type: "string"
            },
            description: {
              type: "string"
            },
            value: {
              type: "string"
            }
          }
        }
      }
    }
  nmi: {
    type: "object",
    additionalProperties: true,
    required: [
      "nmi"
    ],
    properties: {
      nmi: {
        type: "integer"
      }
    }
  }

