openapi: 3.0.1
info:
  title: Outage Publication
  version: DRAFT
  description: |
    __(DRAFT)__ API for EDNAR to provide outage information to external systems (e.g. public website)

tags:
  - name: Outage Publication
paths:
  /outages:
    post:
      tags:
        - Outage Publication
      summary: Used to retrieve data for multiple outages.
      description: |
        Request all outages that meet the criteria included in the request payload.
      requestBody:
        description: The criteria that must be met by the outages that will be returned.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/outageRequest'
        required: false
      responses:
        200:
          description: A list of outage detail objects (one for each returned outage).
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/OutageList'
              example:
                outages:
                  - outageID: 12345
                    status: Ordered
                    location: Bayview
                    startDateTime: '2021-07-20T01:44:07+10:00'
                    endDateTime: '2021-07-20T02:30:00+10:00'
                    alternateStartDate: '2021-07-24T01:30:00+10:00'
                    nmiCount: 125
                    outageReason: Line/cable maintenance
                    cancellationReason: No crews available


components:
  schemas:
    # Requests
    outageRequest:
      required:
        - nmis
      type: object
      properties:
        fromDateTime:
          type: string
          description: Start datetime for range in which outages will be searched
          pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
          example: '2021-07-20T01:44:07+10:00'
        toDateTime:
          type: string
          description: End datetime for range in which outages will be searched
          pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
          example: '2021-07-20T01:44:07+10:00'



    # Data Objects

    # -- OutageList --
    OutageList:
      required:
        - outages
      type: object
      properties:
        outages:
          type: array
          items:
            type: object
            required:
              - outageID
            properties:
              outageID:
                type: string
              status:
                type: string
              location:
                type: string
                description: Location from the NAR title field
                example: Bayview
              startDateTime:
                type: string
                pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
                description: Start datetime of the outage
                example: '2021-07-20T01:44:07+10:00'
              endDateTime:
                type: string
                pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
                description: End datetime of the outage
                example: '2021-07-20T02:30:00+10:00'
              alternateStartDate:
                type: string
                pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
                description: Alternate start datetime of the NAR (not the individual outage)
                example: '2021-07-24T01:30:00+10:00'
              nmiCount:
                type: number
                description: Number of affected customers
                example: 125
              outageReason:
                type: string
                example: Tree-clearing
              cancellationReason:
                type: string
                example: Poor weather forecast




