openapi: 3.0.0
servers:
  - url: "{Evolve App Server}/api/user"
    variables:
      "Evolve App Server":
        default: https://localhost:7654
info:
  title: EAS User API
  version: next
security:
  - Self: []
  - Auth0: []
paths:
  /createUser:
    get:
      tags:
        - User Routes
      summary: Creates a user in the configured database and returns its ID
      description: >-
        This will be deprecated when proper admin controls are implemented.
      operationId: createUser
      parameters:
        - name: username
          in: query
          schema:
            type: string
            example: new_user
      responses:
        '200':
          description: OK
          content:
            'text/plain':
              schema:
                type: string

  /queryUser:
    get:
      tags:
        - User Routes
      summary: Queries a user in the configured database by ID and returns the username
      description: >-
        This will be deprecated when proper admin controls are implemented.
      operationId: queryUser
      parameters:
        - name: id
          in: query
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: OK
          content:
            'text/plain':
              schema:
                type: string
components:
  securitySchemes:
    Self:
      $ref: "../shared-components.yaml#components/securitySchemes/Self"
    Auth0:
      $ref: "../shared-components.yaml#components/securitySchemes/Auth0"
