swagger: "2.0"
info:
  description: "Notification events from EDNAR to CDM. Please note that this API is currently in development. "
  version: "1.0.0"
  title: "Notification Events"
tags:
- name: "notifications"
  description: "Notification events from EDNAR"
schemes:
- "https"
- "http"
paths:
  /notify:
    post:
      tags:
      - "notifications"
      summary: "Operation to send notification to API endpoint."
      description: "All notification events follow the same format (outage notifications, cancellations etc.)"
      operationId: "notifyOutage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "NotifyOutageRequest"
        required: true
        schema:
          $ref: "#/definitions/NotifyOutageRequest"
      - in: "header"
        name: "company"
        type: "string"
        description: ""
      responses:
        "200":
          description: "Success. If the event is a cancellation, the response body will be empty."
          schema:
            $ref: "#/definitions/NotifyOutageResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/fault1"
definitions:
  NotifyOutageRequest:
    type: "object"
    required:
    - type
    - requestedTime
    - nmis
    - plannedOutageReference
    properties:
      type:
        type: "string"
        description: "Type of outage request (new notification, cancellation, updated request etc.).
        Full details of what these codes mean will be included below as they are confirmed: <br><br>
        - PLANNED_C = Cancellation of existing outage"
        enum:
        - "PLANNED_N"
        - "PLANNED_C"
        - "PLANNED_V"
        - "PLANNED_U"
        - "PLANNED_O"
        - "PLANNED_R"
        - "PLANNED_REM"
        - "UNPLANNED_O"
        - "UNPLANNED_R"
        - "UNPLANNED_U"
        - "COR_N"
        - "COR_C"
        - "COR_V"
        - "MAYBE_N"
        - "MAYBE_V"
        - "NAP_N"
        - "BROADCAST"
        - "METER_N"
        - "METER_REM"
        - "METER_APP"
        - "METER_LSC"
      reasonCode:
        type: "string"
        description: "Reason for outage/interruption, cancellation of outage/interruption or update of outage/interruption"
      outageId:
        type: "string"
        description: ""
      sendHandcard:
        type: "boolean"
        description: "True if handcard needs to be sent. Default is false."
        default: false
      requestedTime:
        type: "string"
        pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
        description: "Timestamp of when the event was created in the source system. Format (timezone at the end): yyyy-mm-dd'T'hh:mm:ss[+,-]hh:mm"
        example: "2021-05-10T11:01:33+10:00"
      outageStartTime:
        type: "string"
        pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
        description: "Maps to start time at endpoint"
        example: "2021-07-20T01:44:07+10:00"
      outageEndTime:
        type: "string"
        pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
        description: "Maps to end time in endpoint"
        example: "2021-07-21T01:44:07+10:00"
      template:
        type: "object"
        properties:
          ID:
            type: "string"
        description: "Only if a custom template needs to be issued"
      nmis:
        type: "array"
        items:
          type: "string"
        description: "List of affected National Meter Identifiers (NMIs) or Installation Control Points (ICPs). NMI length is 11 digits, ICP length is 15 characters."
        example: [ "60001234111" ,"60001244222", "60001235111" ]
      plannedOutageReference:
        type: "object"
        required:
        - networkAccessRequestReference
        - taskReference
        properties:
          networkAccessRequestReference:
            type: "string"
            description: "Network Access Request reference (NAR ID)"
          switchingSheetReference:
            type: "string"
            description: "Switch-sheet Number"
          taskReference:
            type: "string"
            description: "Task Reference"
          workOrderId:
            type: "string"
            description: "Work Order ID"
  NotifyOutageResponse:
    type: "object"
    properties:
      header:
        type: "object"
        properties:
          company:
            type: "string"
          ebmId:
            type: "string"
            description: "Unique ID for tracking requests and responses. Used for audit purposes."
      body:
        type: "object"
        properties:
          type:
            type: "string"
            enum:
              - "PLANNED_N"
              - "PLANNED_C"
              - "PLANNED_V"
              - "PLANNED_U"
              - "PLANNED_O"
              - "PLANNED_R"
              - "PLANNED_REM"
              - "UNPLANNED_O"
              - "UNPLANNED_R"
              - "UNPLANNED_U"
              - "COR_N"
              - "COR_C"
              - "COR_V"
              - "MAYBE_N"
              - "MAYBE_V"
              - "NAP_N"
              - "BROADCAST"
              - "METER_N"
              - "METER_REM"
              - "METER_APP"
              - "METER_LSC"
          reasonCode:
            type: "string"
          outageId:
            type: "string"
          sendHandcard:
            type: "boolean"
            default: false
          requestedTime:
            type: "string"
            pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
            example: "2021-05-10T11:01:33+10:00"
          outageStartTime:
            type: "string"
            pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
            example: "2021-07-20T01:44:07+10:00"
          outageEndTime:
            type: "string"
            pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
            example: "2021-07-21T01:44:07+10:00"
          template:
            type: "object"
            properties:
              ID:
                type: "string"
          nmis:
            type: "object"
            properties:
              nmi:
                type: "string"
                description: "Length of 11 digits for NMI, 15 characters for ICP"
              sendTime:
                type: "string"
                description: "Scheduled time of the notification for the NMI"
                pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
              processed:
                type: "boolean"
            description: "One NMI object will be returned for each notification that is scheduled/sent."
            example: [
            {
              "nmi": "60001234111",
              "sendTime": "2021-07-08T00:00:00+10:00",
              "processed": false
            },
            {
              "nmi": "60001244222",
              "sendTime": "2021-07-08T00:00:00+10:00",
              "processed": false
            },
            {
              "nmi": "60001235111",
              "sendTime": "2021-07-08T00:00:00+10:00",
              "processed": false
            }
            ]
          lastSendPostTime:
            type: "string"
            pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
            description: "Internal for CPPAL, currently not handled by EDNAR"
  fault1:
    type: "object"
    properties:
      code:
        type: "string"
        description: "util.fault:001 - Unknown Fault<br>util.fault:002 - Unknown SOAP Fault<br>util.fault:101 - HTTP Endpoint not reachable<br>util.fault:201 - Invalid Payload<br>util.fault:202 - Transformation Failure"
        enum:
          - util.fault:001
          - util.fault:002
          - util.fault:101
          - util.fault:201
          - util.fault:202
      message:
        type: "string"
      timestamp:
        type: "string"
        pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+,-]\d\d:\d\d$'
        example: "2021-05-10T11:01:33+10:00"
      errors:
        type: "array"
        items:
          $ref: "#/definitions/Errors"
  Errors:
    type: "object"
    properties:
      elementName:
        type: "string"
      errorMessage:
        type: "string"
    example: [
    {
      "elementName": "type",
      "errorMessage": "type is null"
    },
    {
      "elementName": "outageStartTime",
      "errorMessage": "outageStartTime is invalid"
    },
    {
      "elementName": "outageEndTime",
      "errorMessage": "outageEndTime is invalid"
    }
    ]
