openapi: 3.0.0
servers:
  - url: "{Evolve App Server}/api/config"
    variables:
      "Evolve App Server":
        default: https://localhost:7654
info:
  title: EAS Config API
  version: next
security:
  - Auth0: []
paths:
  /auth:
    get:
      tags:
        - Auth Config
      summary: Retrieve the auth config
      description: >-
        Used to retrieve auth related config for use by clients
      operationId: authConfig
      security: []
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
                properties:
                  configType:
                    type: string
components:
  securitySchemes:
    Auth0:
      $ref: "../shared-components.yaml#components/securitySchemes/Auth0"
