openapi: 3.0.0
servers:
  - url: /ewb/store/api
info:
  version: 1.7.1
  title: EWB Store API
  license:
    name: Zeppelin Bend
tags:
  - name: Store v1
paths:
  /v1/{id}/key/{key}/value{value}:
    $ref: 'v1-route-id-key-value.yaml'
  /v1/{id}/key/{key}:
    $ref: 'v1-route-id-key.yaml'
  /v1/{id}:
    $ref: 'v1-route-id.yaml'
