name: Manual Deploy Evolve docs

on: 
  workflow_dispatch:
    inputs:
      product:
        description: 'Product to deploy the docs for, evolve or ednar'
        required: true
        type: choice
        options:
          - "evolve"
          - "ednar"
      repository:
        description: 'Repository of the project to deploy the docs for'
        required: true
      artifact:
        description: 'The artifact id to deploy'
        required: true
      run-id:
        description: 'The run id of the action that created the artifact'
        required: true
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy documentation
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: ${{ secrets.DOCS_REPO }}
          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
          client-payload: '{"product": "${{ inputs.product}}", "repository": "${{ inputs.repository }}", "artifact": "${{ inputs.artifact }}", "run-id": "${{ inputs.run-id }}"}'
